set dotenv-load

export EDITOR := 'nvim'

alias f := fmt
alias tc := typecheck

default:
  just --list

fmt:
   uv run ruff check --select I --fix && uv run ruff format

install:
  uv pip install --force-reinstall --no-deps --editable ../py

typecheck:
  uv run ty check
